from pathlib import Path

path = Path('public/index.html')
html = path.read_text(encoding='utf-8')

old = "function renderLive(){const L=BASE?.latest;if(!L)return;const liveLv=LIVE?.models?.niveles?.vc_intraday,liveRv=LIVE?.models?.retornos?.vc_intraday,liveRr=LIVE?.models?.retornos?.return_intraday,lv=finite(liveLv)?Number(liveLv):Number(L.vc_niveles),rv=finite(liveRv)?Number(liveRv):Number(L.vc_retornos),rows=BASE?.rows||[],prev=rows.at(-2),lr=finite(liveLv)&&finite(L.vc_niveles)&&Number(L.vc_niveles)!==0?Number(liveLv)/Number(L.vc_niveles)-1:prev&&finite(prev.vc_niveles)&&Number(prev.vc_niveles)!==0?Number(L.vc_niveles)/Number(prev.vc_niveles)-1:null,rr=finite(liveRr)?Number(liveRr):finite(L.ret_vc_estimado)?Number(L.ret_vc_estimado):null,mode=LIVE?LIVE.mode:'CIERRE';$('levelsVc').textContent=vc(lv);$('returnsVc').textContent=vc(rv);$('levNow').textContent=vc(lv);$('retNow').textContent=vc(rv);$('levNowPct').textContent=pct(lr);$('levNowPct').className=cls(lr);$('retNowPct').textContent=pct(rr);$('retNowPct').className=cls(rr);$('levelsLive').textContent=`${mode} · variación ${pct(lr)}`;$('levelsLive').className='signal '+cls(lr);$('returnsLive').textContent=`${mode} · variación ${pct(rr)}`;$('returnsLive').className='signal '+cls(rr);if(LIVE){$('marketDate').textContent=dFmt(LIVE.signal_date);$('marketMode').textContent=LIVE.market_open?'MERCADO ABIERTO · DATOS INTRADÍA':'MERCADO CERRADO · ÚLTIMO DATO';$('marketMode').className='signal marketstate';$('marketStamp').textContent='Corte: '+new Date(LIVE.generated_at_lima).toLocaleString('es-PE')}}"

new = "function renderLive(){const L=BASE?.latest;if(!L)return;const liveLv=LIVE?.models?.niveles?.vc_intraday,liveRv=LIVE?.models?.retornos?.vc_intraday,liveRr=LIVE?.models?.retornos?.return_intraday,rows=BASE?.rows||[],prev=rows.at(-2),lastRet=[...rows].reverse().find(z=>finite(z.vc_retornos)),retBase=finite(LIVE?.models?.retornos?.base_vc)?Number(LIVE.models.retornos.base_vc):finite(L.vc_retornos)?Number(L.vc_retornos):lastRet?Number(lastRet.vc_retornos):null,lv=finite(liveLv)?Number(liveLv):finite(L.vc_niveles)?Number(L.vc_niveles):null,rv=finite(liveRv)?Number(liveRv):finite(L.vc_retornos)?Number(L.vc_retornos):retBase,lr=finite(liveLv)&&finite(L.vc_niveles)&&Number(L.vc_niveles)!==0?Number(liveLv)/Number(L.vc_niveles)-1:prev&&finite(prev.vc_niveles)&&Number(prev.vc_niveles)!==0?Number(L.vc_niveles)/Number(prev.vc_niveles)-1:null,rr=finite(liveRr)?Number(liveRr):finite(L.ret_vc_estimado)?Number(L.ret_vc_estimado):null,mode=LIVE?LIVE.mode:'CIERRE';$('levelsVc').textContent=vc(lv);$('returnsVc').textContent=vc(rv);$('levClose').textContent=vc(L.vc_niveles);$('retClose').textContent=vc(retBase);$('levNow').textContent=vc(lv);$('retNow').textContent=vc(rv);$('levNowPct').textContent=pct(lr);$('levNowPct').className=cls(lr);$('retNowPct').textContent=pct(rr);$('retNowPct').className=cls(rr);$('levelsLive').textContent=`${mode} · variación ${pct(lr)}`;$('levelsLive').className='signal '+cls(lr);$('returnsLive').textContent=`${mode} · variación ${pct(rr)}`;$('returnsLive').className='signal '+cls(rr);if(LIVE){$('marketDate').textContent=dFmt(LIVE.signal_date);$('marketMode').textContent=LIVE.market_open?'MERCADO ABIERTO · DATOS INTRADÍA':'MERCADO CERRADO · ÚLTIMO DATO';$('marketMode').className='signal marketstate';$('marketStamp').textContent='Corte: '+new Date(LIVE.generated_at_lima).toLocaleString('es-PE')}}"

if new in html:
    print('Profuturo: base de retorno ya alineada.')
elif old in html:
    path.write_text(html.replace(old, new, 1), encoding='utf-8')
    print('Profuturo: base de retorno alineada con el snapshot intradía.')
else:
    raise RuntimeError('No se encontró la función renderLive esperada; no se aplica un cambio inseguro.')
